#!/usr/bin/env python3

def build(bld):
    # CORE_JSON component
    if bld.is_defined('CONFIG_CORE_JSON'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'components/core_json/core_json.c'
        ]