#!/usr/bin/env python3

def build(bld):
    # QSPI driver
#   if bld.is_defined('CONFIG_USING_QSPI'):
    bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/qspi/drv_spi_device.c',
            'drivers/qspi/spi-cadence-quadspi.c',
            'drivers/qspi/spi-device.c',
        ]
