#!/usr/bin/env python3

def build(bld):
    # GPIO driver
    if bld.is_defined('CONFIG_DRIVER_GPIO'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
                'drivers/gpio/drv_gpio.c',
            ]
