#!/usr/bin/env python3

def build(bld):
    # TRNG driver
    if bld.is_defined('CONFIG_DRIVER_TRNG_DW'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/trng/drv_trng_dw.c'
        ]

    if bld.is_defined('CONFIG_DRIVER_TRNG_TH'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/trng/drv_trng_th.c'
        ]

