/**
 * Copyright (C), 2020, WuXi Stars Micro System Technologies Co., Ltd.
 *
 * @file    osp_inner_sysinit.h
 * @author  lichenxiang
 * @date    2020.10.28
 * @brief   系统初始化入口的内部定义
 * @note    NA
 */

#ifndef __OSP_INNER_SYSINIT_H
#define __OSP_INNER_SYSINIT_H

#ifndef __OSP_SYSINIT_H
#error "include osp_mutex.h instead include this header file"
#endif

#include <rtems/sysinit.h>

#ifdef __cplusplus
extern "C" {
#endif

///< MODULE
#define OSP_INNER_SYSINIT_RECORD                     RTEMS_SYSINIT_RECORD
#define OSP_INNER_SYSINIT_BSP_EARLY                  RTEMS_SYSINIT_BSP_EARLY
#define OSP_INNER_SYSINIT_MEMORY                     RTEMS_SYSINIT_MEMORY
#define OSP_INNER_SYSINIT_DIRTY_MEMORY               RTEMS_SYSINIT_DIRTY_MEMORY
#define OSP_INNER_SYSINIT_ZERO_MEMORY                RTEMS_SYSINIT_ZERO_MEMORY
#define OSP_INNER_SYSINIT_ISR_STACK                  RTEMS_SYSINIT_ISR_STACK
#define OSP_INNER_SYSINIT_PER_CPU_DATA               RTEMS_SYSINIT_PER_CPU_DATA
#define OSP_INNER_SYSINIT_SBRK                       RTEMS_SYSINIT_SBRK
#define OSP_INNER_SYSINIT_WORKSPACE                  RTEMS_SYSINIT_WORKSPACE
#define OSP_INNER_SYSINIT_MALLOC                     RTEMS_SYSINIT_MALLOC
#define OSP_INNER_SYSINIT_BSP_START                  RTEMS_SYSINIT_BSP_START
#define OSP_INNER_SYSINIT_CPU_COUNTER                RTEMS_SYSINIT_CPU_COUNTER
#define OSP_INNER_SYSINIT_INITIAL_EXTENSIONS         RTEMS_SYSINIT_INITIAL_EXTENSIONS
#define OSP_INNER_SYSINIT_MP_EARLY                   RTEMS_SYSINIT_MP_EARLY
#define OSP_INNER_SYSINIT_DATA_STRUCTURES            RTEMS_SYSINIT_DATA_STRUCTURES
#define OSP_INNER_SYSINIT_MP                         RTEMS_SYSINIT_MP
#define OSP_INNER_SYSINIT_USER_EXTENSIONS            RTEMS_SYSINIT_USER_EXTENSIONS
#define OSP_INNER_SYSINIT_CLASSIC_TASKS              RTEMS_SYSINIT_CLASSIC_TASKS
#define OSP_INNER_SYSINIT_CLASSIC_TASKS_MP           RTEMS_SYSINIT_CLASSIC_TASKS_MP
#define OSP_INNER_SYSINIT_CLASSIC_TIMER              RTEMS_SYSINIT_CLASSIC_TIMER
#define OSP_INNER_SYSINIT_CLASSIC_SIGNAL_MP          RTEMS_SYSINIT_CLASSIC_SIGNAL_MP
#define OSP_INNER_SYSINIT_CLASSIC_EVENT_MP           RTEMS_SYSINIT_CLASSIC_EVENT_MP
#define OSP_INNER_SYSINIT_CLASSIC_MESSAGE_QUEUE      RTEMS_SYSINIT_CLASSIC_MESSAGE_QUEUE
#define OSP_INNER_SYSINIT_CLASSIC_MESSAGE_QUEUE_MP   RTEMS_SYSINIT_CLASSIC_MESSAGE_QUEUE_MP
#define OSP_INNER_SYSINIT_CLASSIC_SEMAPHORE          RTEMS_SYSINIT_CLASSIC_SEMAPHORE
#define OSP_INNER_SYSINIT_CLASSIC_SEMAPHORE_MP       RTEMS_SYSINIT_CLASSIC_SEMAPHORE_MP
#define OSP_INNER_SYSINIT_CLASSIC_PARTITION          RTEMS_SYSINIT_CLASSIC_PARTITION
#define OSP_INNER_SYSINIT_CLASSIC_PARTITION_MP       RTEMS_SYSINIT_CLASSIC_PARTITION_MP
#define OSP_INNER_SYSINIT_CLASSIC_REGION             RTEMS_SYSINIT_CLASSIC_REGION
#define OSP_INNER_SYSINIT_CLASSIC_DUAL_PORTED_MEMORY RTEMS_SYSINIT_CLASSIC_DUAL_PORTED_MEMORY
#define OSP_INNER_SYSINIT_CLASSIC_RATE_MONOTONIC     RTEMS_SYSINIT_CLASSIC_RATE_MONOTONIC
#define OSP_INNER_SYSINIT_CLASSIC_BARRIER            RTEMS_SYSINIT_CLASSIC_BARRIER
#define OSP_INNER_SYSINIT_POSIX_SIGNALS              RTEMS_SYSINIT_POSIX_SIGNALS
#define OSP_INNER_SYSINIT_POSIX_THREADS              RTEMS_SYSINIT_POSIX_THREADS
#define OSP_INNER_SYSINIT_POSIX_MESSAGE_QUEUE        RTEMS_SYSINIT_POSIX_MESSAGE_QUEUE
#define OSP_INNER_SYSINIT_POSIX_SEMAPHORE            RTEMS_SYSINIT_POSIX_SEMAPHORE
#define OSP_INNER_SYSINIT_POSIX_TIMER                RTEMS_SYSINIT_POSIX_TIMER
#define OSP_INNER_SYSINIT_POSIX_SHM                  RTEMS_SYSINIT_POSIX_SHM
#define OSP_INNER_SYSINIT_POSIX_KEYS                 RTEMS_SYSINIT_POSIX_KEYS
#define OSP_INNER_SYSINIT_POSIX_CLEANUP              RTEMS_SYSINIT_POSIX_CLEANUP
#define OSP_INNER_SYSINIT_IDLE_THREADS               RTEMS_SYSINIT_IDLE_THREADS
#define OSP_INNER_SYSINIT_LIBIO                      RTEMS_SYSINIT_LIBIO
#define OSP_INNER_SYSINIT_USER_ENVIRONMENT           RTEMS_SYSINIT_USER_ENVIRONMENT
#define OSP_INNER_SYSINIT_ROOT_FILESYSTEM            RTEMS_SYSINIT_ROOT_FILESYSTEM
#define OSP_INNER_SYSINIT_DRVMGR                     RTEMS_SYSINIT_DRVMGR
#define OSP_INNER_SYSINIT_MP_SERVER                  RTEMS_SYSINIT_MP_SERVER
#define OSP_INNER_SYSINIT_BSP_PRE_DRIVERS            RTEMS_SYSINIT_BSP_PRE_DRIVERS
#define OSP_INNER_SYSINIT_DRVMGR_LEVEL_1             RTEMS_SYSINIT_DRVMGR_LEVEL_1
#define OSP_INNER_SYSINIT_DEVICE_DRIVERS             RTEMS_SYSINIT_DEVICE_DRIVERS
#define OSP_INNER_SYSINIT_DRVMGR_LEVEL_2             RTEMS_SYSINIT_DRVMGR_LEVEL_2
#define OSP_INNER_SYSINIT_DRVMGR_LEVEL_3             RTEMS_SYSINIT_DRVMGR_LEVEL_3
#define OSP_INNER_SYSINIT_DRVMGR_LEVEL_4             RTEMS_SYSINIT_DRVMGR_LEVEL_4
#define OSP_INNER_SYSINIT_MP_FINALIZE                RTEMS_SYSINIT_MP_FINALIZE
#define OSP_INNER_SYSINIT_CLASSIC_USER_TASKS         RTEMS_SYSINIT_CLASSIC_USER_TASKS
#define OSP_INNER_SYSINIT_POSIX_USER_THREADS         RTEMS_SYSINIT_POSIX_USER_THREADS
#define OSP_INNER_SYSINIT_STD_FILE_DESCRIPTORS       RTEMS_SYSINIT_STD_FILE_DESCRIPTORS
#define OSP_INNER_SYSINIT_LAST                       RTEMS_SYSINIT_LAST

///< ORDER
#define OSP_INNER_SYSINIT_ORDER_FIRST      RTEMS_SYSINIT_ORDER_FIRST
#define OSP_INNER_SYSINIT_ORDER_SECOND     RTEMS_SYSINIT_ORDER_SECOND
#define OSP_INNER_SYSINIT_ORDER_THIRD      RTEMS_SYSINIT_ORDER_THIRD
#define OSP_INNER_SYSINIT_ORDER_FOURTH     RTEMS_SYSINIT_ORDER_FOURTH
#define OSP_INNER_SYSINIT_ORDER_FIFTH      RTEMS_SYSINIT_ORDER_FIFTH
#define OSP_INNER_SYSINIT_ORDER_SIXTH      RTEMS_SYSINIT_ORDER_SIXTH
#define OSP_INNER_SYSINIT_ORDER_SEVENTH    RTEMS_SYSINIT_ORDER_SEVENTH
#define OSP_INNER_SYSINIT_ORDER_EIGHTH     RTEMS_SYSINIT_ORDER_EIGHTH
#define OSP_INNER_SYSINIT_ORDER_NINETH     RTEMS_SYSINIT_ORDER_NINETH
#define OSP_INNER_SYSINIT_ORDER_TENTH      RTEMS_SYSINIT_ORDER_TENTH
#define OSP_INNER_SYSINIT_ORDER_MIDDLE     RTEMS_SYSINIT_ORDER_MIDDLE
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_9 RTEMS_SYSINIT_ORDER_LAST_BUT_9
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_8 RTEMS_SYSINIT_ORDER_LAST_BUT_8
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_7 RTEMS_SYSINIT_ORDER_LAST_BUT_7
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_6 RTEMS_SYSINIT_ORDER_LAST_BUT_6
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_5 RTEMS_SYSINIT_ORDER_LAST_BUT_5
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_4 RTEMS_SYSINIT_ORDER_LAST_BUT_4
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_3 RTEMS_SYSINIT_ORDER_LAST_BUT_3
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_2 RTEMS_SYSINIT_ORDER_LAST_BUT_2
#define OSP_INNER_SYSINIT_ORDER_LAST_BUT_1 RTEMS_SYSINIT_ORDER_LAST_BUT_1
#define OSP_INNER_SYSINIT_ORDER_LAST       RTEMS_SYSINIT_ORDER_LAST

typedef rtems_sysinit_handler OSPInnerSysinitHandler;
typedef rtems_sysinit_item OSPInnerSysinitItem;

#define OSP_INNER_SYSINIT_ITEM(handler, module, order) RTEMS_SYSINIT_ITEM(handler, module, order)

#ifdef __cplusplus
}
#endif
#endif
