#!/usr/bin/env python3

def build(bld):
    # Timer driver
    if bld.is_defined('CONFIG_DRIVER_TIMER'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/timer/drv_timer.c'
        ]