#!/usr/bin/env python3

def build(bld):
    # MISC component
    #if bld.is_defined('CONFIG_USING_MISC'):
    bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'components/misc/stringto_wrapper.c',
            'components/misc/udelay.c',
            'components/misc/verify.c',
            'components/misc/version.c',
        ]
