#!/usr/bin/env python3

def build(bld):
    # SBR component
    if bld.is_defined('CONFIG_ENABLE_SBR_API'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
                'components/sbr/sbr_api.c',
            ]
