#!/usr/bin/env python3

def build(bld):
    # Security drivers
    if bld.is_defined('CONFIG_DRIVER_EFUSE_V1'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/security/efuse/drv_efuse_v1.c'
        ]

    if bld.is_defined('CONFIG_DRIVER_EFUSE_V2'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/security/efuse/drv_efuse_v2.c'
        ]

    if bld.is_defined('CONFIG_DRIVER_TRNG_DW'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/security/trng/drv_trng_dw.c'
        ]

    if bld.is_defined('CONFIG_DRIVER_TRNG_TH'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/security/trng/drv_trng_th.c'
        ]

    if bld.is_defined('CONFIG_DRIVER_SM3'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/security/sm3/drv_sm3.c'
        ]
    if bld.is_defined('CONFIG_DRIVER_SM2'):

        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/security/sm2/drv_sm2.c'
        ]

    if bld.is_defined('CONFIG_USING_SM4'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/security/sm4/drv_sm4.c'
        ]
