#!/usr/bin/env python3

def build(bld):
    # OCM ECC driver
    if bld.is_defined('CONFIG_USING_OCM_ECC'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/ocm_ecc/drv_ocm_ecc.c'
        ]
