#!/usr/bin/env python3

def build(bld):
    # TACH driver
    if bld.is_defined('CONFIG_USING_TACH'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/tach/drv_tach.c'
        ]