#!/usr/bin/env python3

def build(bld):
    # SM4 driver
    if bld.is_defined('CONFIG_DRIVER_SM4'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/sm4/drv_sm4.c'
        ]

