
/**
 * Copyright (C), 2024, WuXi Stars Micro System Technologies Co.,Ltd
 *
 * @file bsp_device.c
 * @author shaogl (taohb@starsmicrosystem.com)
 * @date 2025/05/24
 * @brief bsp device defines.
 *
 * @par ChangeLog:
 *
 * Date         Author          Description
 * 2025/05/24   taohb        the first version
 */

#include "common_defines.h"
#include "bsp_device.h"
#include "bsp_api.h"

static Device_s sysDev[] = {
    DEVICE_CONSTRUCTOR(UART0, uart0, DRV_ID_STARS_UART),
    DEVICE_CONSTRUCTOR(GPIO0, gpio0, DRV_ID_STARS_GPIO),
    DEVICE_CONSTRUCTOR(GPIO1, gpio1, DRV_ID_STARS_GPIO),
    DEVICE_CONSTRUCTOR(TRNG0, trng0, DRV_ID_HG_TRNG),
    DEVICE_CONSTRUCTOR(WDT0, wdt0, DRV_ID_STARS_WDT),
    DEVICE_CONSTRUCTOR(WDT1, wdt1, DRV_ID_STARS_WDT),
    DEVICE_CONSTRUCTOR(WDT2, wdt2, DRV_ID_STARS_WDT),
    DEVICE_CONSTRUCTOR(WDT3, wdt3, DRV_ID_STARS_WDT),
    DEVICE_CONSTRUCTOR(EFUSE0, efuse0, DRV_ID_STARS_V2_EFUSE),
    DEVICE_CONSTRUCTOR(PWM0, pwm0, DRV_ID_STARS_PWM),
    DEVICE_CONSTRUCTOR(SMBUS0, smbus0, DRV_ID_DW_I2C),
    DEVICE_CONSTRUCTOR(SMBUS1, smbus1, DRV_ID_DW_I2C),
    DEVICE_CONSTRUCTOR(SGPIO0, sgpio0, DRV_ID_STARS_V1P0_SGPIO),
    DEVICE_CONSTRUCTOR(SGPIO1, sgpio1, DRV_ID_STARS_V1P0_SGPIO),
    DEVICE_CONSTRUCTOR(SGPIO2, sgpio2, DRV_ID_STARS_V1P0_SGPIO),
    DEVICE_CONSTRUCTOR(SGPIO3, sgpio3, DRV_ID_STARS_V1P0_SGPIO),
    DEVICE_CONSTRUCTOR(OCM_ECC, ocm_ecc, DRV_ID_STARS_OCM_ECC),
    DEVICE_CONSTRUCTOR(SM3_0, sm3_0, DRV_ID_STARS_SM3),
    DEVICE_CONSTRUCTOR(TACH0, tach0, DRV_ID_STARS_TACH),
    DEVICE_CONSTRUCTOR(TACH1, tach1, DRV_ID_STARS_TACH),
    DEVICE_CONSTRUCTOR(TACH2, tach2, DRV_ID_STARS_TACH),
    DEVICE_CONSTRUCTOR(TACH3, tach3, DRV_ID_STARS_TACH),
    DEVICE_CONSTRUCTOR(SM2_0, sm2_0, DRV_ID_STARS_SM2),
    DEVICE_CONSTRUCTOR(TIMER0, timer0, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER1, timer1, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER2, timer2, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER3, timer3, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER4, timer4, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER5, timer5, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER6, timer6, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER7, timer7, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER8, timer8, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER9, timer9, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER10, timer10, DRV_ID_STARS_TIMER),
    DEVICE_CONSTRUCTOR(TIMER11, timer11, DRV_ID_STARS_TIMER),
};

Device_s* getDevList(void)
{
    return sysDev;
}

U32 getDevSize(void)
{
    return ARRAY_SIZE(sysDev);
}
