#!/usr/bin/env python3

def build(bld):
    # WDT driver
    if bld.is_defined('CONFIG_DRIVER_WDT'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/wdt/drv_wdt.c'
        ]