/**
 * Copyright (C), 2020, WuXi Stars Micro System Technologies Co., Ltd.
 *
 * @file    osp_sysinit.h
 * @author  lichenxiang
 * @date    2020.10.28
 * @brief   系统初始化入口(驱动使用)
 * @note    NA
 */

#ifndef __OSP_SYSINIT_H
#define __OSP_SYSINIT_H

#include <inner/osp_inner_sysinit.h>
#ifdef __cplusplus
extern "C" {
#endif

///< MODULE
#define OSP_SYSINIT_RECORD                     OSP_INNER_SYSINIT_RECORD
#define OSP_SYSINIT_BSP_EARLY                  OSP_INNER_SYSINIT_BSP_EARLY
#define OSP_SYSINIT_MEMORY                     OSP_INNER_SYSINIT_MEMORY
#define OSP_SYSINIT_DIRTY_MEMORY               OSP_INNER_SYSINIT_DIRTY_MEMORY
#define OSP_SYSINIT_ZERO_MEMORY                OSP_INNER_SYSINIT_ZERO_MEMORY
#define OSP_SYSINIT_ISR_STACK                  OSP_INNER_SYSINIT_ISR_STACK
#define OSP_SYSINIT_PER_CPU_DATA               OSP_INNER_SYSINIT_PER_CPU_DATA
#define OSP_SYSINIT_SBRK                       OSP_INNER_SYSINIT_SBRK
#define OSP_SYSINIT_WORKSPACE                  OSP_INNER_SYSINIT_WORKSPACE
#define OSP_SYSINIT_MALLOC                     OSP_INNER_SYSINIT_MALLOC
#define OSP_SYSINIT_BSP_START                  OSP_INNER_SYSINIT_BSP_START
#define OSP_SYSINIT_CPU_COUNTER                OSP_INNER_SYSINIT_CPU_COUNTER
#define OSP_SYSINIT_INITIAL_EXTENSIONS         OSP_INNER_SYSINIT_INITIAL_EXTENSIONS
#define OSP_SYSINIT_MP_EARLY                   OSP_INNER_SYSINIT_MP_EARLY
#define OSP_SYSINIT_DATA_STRUCTURES            OSP_INNER_SYSINIT_DATA_STRUCTURES
#define OSP_SYSINIT_MP                         OSP_INNER_SYSINIT_MP
#define OSP_SYSINIT_USER_EXTENSIONS            OSP_INNER_SYSINIT_USER_EXTENSIONS
#define OSP_SYSINIT_CLASSIC_TASKS              OSP_INNER_SYSINIT_CLASSIC_TASKS
#define OSP_SYSINIT_CLASSIC_TASKS_MP           OSP_INNER_SYSINIT_CLASSIC_TASKS_MP
#define OSP_SYSINIT_CLASSIC_TIMER              OSP_INNER_SYSINIT_CLASSIC_TIMER
#define OSP_SYSINIT_CLASSIC_SIGNAL_MP          OSP_INNER_SYSINIT_CLASSIC_SIGNAL_MP
#define OSP_SYSINIT_CLASSIC_EVENT_MP           OSP_INNER_SYSINIT_CLASSIC_EVENT_MP
#define OSP_SYSINIT_CLASSIC_MESSAGE_QUEUE      OSP_INNER_SYSINIT_CLASSIC_MESSAGE_QUEUE
#define OSP_SYSINIT_CLASSIC_MESSAGE_QUEUE_MP   OSP_INNER_SYSINIT_CLASSIC_MESSAGE_QUEUE_MP
#define OSP_SYSINIT_CLASSIC_SEMAPHORE          OSP_INNER_SYSINIT_CLASSIC_SEMAPHORE
#define OSP_SYSINIT_CLASSIC_SEMAPHORE_MP       OSP_INNER_SYSINIT_CLASSIC_SEMAPHORE_MP
#define OSP_SYSINIT_CLASSIC_PARTITION          OSP_INNER_SYSINIT_CLASSIC_PARTITION
#define OSP_SYSINIT_CLASSIC_PARTITION_MP       OSP_INNER_SYSINIT_CLASSIC_PARTITION_MP
#define OSP_SYSINIT_CLASSIC_REGION             OSP_INNER_SYSINIT_CLASSIC_REGION
#define OSP_SYSINIT_CLASSIC_DUAL_PORTED_MEMORY OSP_INNER_SYSINIT_CLASSIC_DUAL_PORTED_MEMORY
#define OSP_SYSINIT_CLASSIC_RATE_MONOTONIC     OSP_INNER_SYSINIT_CLASSIC_RATE_MONOTONIC
#define OSP_SYSINIT_CLASSIC_BARRIER            OSP_INNER_SYSINIT_CLASSIC_BARRIER
#define OSP_SYSINIT_POSIX_SIGNALS              OSP_INNER_SYSINIT_POSIX_SIGNALS
#define OSP_SYSINIT_POSIX_THREADS              OSP_INNER_SYSINIT_POSIX_THREADS
#define OSP_SYSINIT_POSIX_MESSAGE_QUEUE        OSP_INNER_SYSINIT_POSIX_MESSAGE_QUEUE
#define OSP_SYSINIT_POSIX_SEMAPHORE            OSP_INNER_SYSINIT_POSIX_SEMAPHORE
#define OSP_SYSINIT_POSIX_TIMER                OSP_INNER_SYSINIT_POSIX_TIMER
#define OSP_SYSINIT_POSIX_SHM                  OSP_INNER_SYSINIT_POSIX_SHM
#define OSP_SYSINIT_POSIX_KEYS                 OSP_INNER_SYSINIT_POSIX_KEYS
#define OSP_SYSINIT_POSIX_CLEANUP              OSP_INNER_SYSINIT_POSIX_CLEANUP
#define OSP_SYSINIT_IDLE_THREADS               OSP_INNER_SYSINIT_IDLE_THREADS
#define OSP_SYSINIT_LIBIO                      OSP_INNER_SYSINIT_LIBIO
#define OSP_SYSINIT_USER_ENVIRONMENT           OSP_INNER_SYSINIT_USER_ENVIRONMENT
#define OSP_SYSINIT_ROOT_FILESYSTEM            OSP_INNER_SYSINIT_ROOT_FILESYSTEM
#define OSP_SYSINIT_DRVMGR                     OSP_INNER_SYSINIT_DRVMGR
#define OSP_SYSINIT_MP_SERVER                  OSP_INNER_SYSINIT_MP_SERVER
#define OSP_SYSINIT_BSP_PRE_DRIVERS            OSP_INNER_SYSINIT_BSP_PRE_DRIVERS
#define OSP_SYSINIT_DRVMGR_LEVEL_1             OSP_INNER_SYSINIT_DRVMGR_LEVEL_1
#define OSP_SYSINIT_DEVICE_DRIVERS             OSP_INNER_SYSINIT_DEVICE_DRIVERS
#define OSP_SYSINIT_DRVMGR_LEVEL_2             OSP_INNER_SYSINIT_DRVMGR_LEVEL_2
#define OSP_SYSINIT_DRVMGR_LEVEL_3             OSP_INNER_SYSINIT_DRVMGR_LEVEL_3
#define OSP_SYSINIT_DRVMGR_LEVEL_4             OSP_INNER_SYSINIT_DRVMGR_LEVEL_4
#define OSP_SYSINIT_MP_FINALIZE                OSP_INNER_SYSINIT_MP_FINALIZE
#define OSP_SYSINIT_CLASSIC_USER_TASKS         OSP_INNER_SYSINIT_CLASSIC_USER_TASKS
#define OSP_SYSINIT_POSIX_USER_THREADS         OSP_INNER_SYSINIT_POSIX_USER_THREADS
#define OSP_SYSINIT_STD_FILE_DESCRIPTORS       OSP_INNER_SYSINIT_STD_FILE_DESCRIPTORS
#define OSP_SYSINIT_LAST                       OSP_INNER_SYSINIT_LAST

///< ORDER
#define OSP_SYSINIT_ORDER_FIRST      OSP_INNER_SYSINIT_ORDER_FIRST
#define OSP_SYSINIT_ORDER_SECOND     OSP_INNER_SYSINIT_ORDER_SECOND
#define OSP_SYSINIT_ORDER_THIRD      OSP_INNER_SYSINIT_ORDER_THIRD
#define OSP_SYSINIT_ORDER_FOURTH     OSP_INNER_SYSINIT_ORDER_FOURTH
#define OSP_SYSINIT_ORDER_FIFTH      OSP_INNER_SYSINIT_ORDER_FIFTH
#define OSP_SYSINIT_ORDER_SIXTH      OSP_INNER_SYSINIT_ORDER_SIXTH
#define OSP_SYSINIT_ORDER_SEVENTH    OSP_INNER_SYSINIT_ORDER_SEVENTH
#define OSP_SYSINIT_ORDER_EIGHTH     OSP_INNER_SYSINIT_ORDER_EIGHTH
#define OSP_SYSINIT_ORDER_NINETH     OSP_INNER_SYSINIT_ORDER_NINETH
#define OSP_SYSINIT_ORDER_TENTH      OSP_INNER_SYSINIT_ORDER_TENTH
#define OSP_SYSINIT_ORDER_MIDDLE     OSP_INNER_SYSINIT_ORDER_MIDDLE
#define OSP_SYSINIT_ORDER_LAST_BUT_9 OSP_INNER_SYSINIT_ORDER_LAST_BUT_9
#define OSP_SYSINIT_ORDER_LAST_BUT_8 OSP_INNER_SYSINIT_ORDER_LAST_BUT_8
#define OSP_SYSINIT_ORDER_LAST_BUT_7 OSP_INNER_SYSINIT_ORDER_LAST_BUT_7
#define OSP_SYSINIT_ORDER_LAST_BUT_6 OSP_INNER_SYSINIT_ORDER_LAST_BUT_6
#define OSP_SYSINIT_ORDER_LAST_BUT_5 OSP_INNER_SYSINIT_ORDER_LAST_BUT_5
#define OSP_SYSINIT_ORDER_LAST_BUT_4 OSP_INNER_SYSINIT_ORDER_LAST_BUT_4
#define OSP_SYSINIT_ORDER_LAST_BUT_3 OSP_INNER_SYSINIT_ORDER_LAST_BUT_3
#define OSP_SYSINIT_ORDER_LAST_BUT_2 OSP_INNER_SYSINIT_ORDER_LAST_BUT_2
#define OSP_SYSINIT_ORDER_LAST_BUT_1 OSP_INNER_SYSINIT_ORDER_LAST_BUT_1
#define OSP_SYSINIT_ORDER_LAST       OSP_INNER_SYSINIT_ORDER_LAST

typedef OSPInnerSysinitHandler OSPSysinitHandler;
typedef OSPInnerSysinitItem OSPSysinitItem;

#define OSP_SYSINIT_ITEM(handler, module, order) OSP_INNER_SYSINIT_ITEM(handler, module, order)

#ifdef __cplusplus
}
#endif
#endif
