#!/usr/bin/env python3

def build(bld):
    # SGPIO driver
    if bld.is_defined('CONFIG_USING_SGPIO_V2_0'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/sgpio/drv_sgpio_v2.0.c'
        ]
    if bld.is_defined('CONFIG_USING_SGPIO_V1_1'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/sgpio/drv_sgpio_v1.1.c'
        ]
    if bld.is_defined('CONFIG_USING_SGPIO_V1_0'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/sgpio/drv_sgpio_v1.0.c'
        ]