#!/usr/bin/env python3

def build(bld):
    # Build all driver subdirectories
    driver_dirs = [
        'timer', 'uart', 'soc_ctrl', 'gpio', 'wdt', 'tach',
        'sgpio', 'pwm', 'qspi', 'security', 'smbus',
        'pvt', 'qspi_ctrl', 'brd_init', 'ocm_ecc'
    ]
    
    for driver_dir in driver_dirs:
        bld.recurse(driver_dir)
