#!/usr/bin/env python3

def build(bld):
    # SM2 driver
    if bld.is_defined('CONFIG_DRIVER_SM2'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/sm2/drv_sm2.c'
        ]

