#ifndef __BSP_DRV_ID_H__
#define __BSP_DRV_ID_H__

typedef enum DevType {
    DEV_TYPE_BRD_INIT = 0,
    DEV_TYPE_IOMUX,
    DEV_TYPE_MISC,
    DEV_TYPE_GPIO,
    DEV_TYPE_I2C,
    DEV_TYPE_QSPI,
    DEV_TYPE_UART,
    DEV_TYPE_WDT,
    DEV_TYPE_PWM,
    DEV_TYPE_TIMER,
    DEV_TYPE_WATCHDOG,
    DEV_TYPE_PVT,
    DEV_TYPE_TRNG,
    DEV_TYPE_EFUSE,
    DEV_TYPE_SGPIO,
    DEV_TYPE_OCM_ECC,
    DEV_TYPE_SM3,
    DEV_TYPE_TACH,
    DEV_TYPE_SM2,
    DEV_TYPE_SM4,

} DevType_e;

typedef enum DrvId {
    DRV_ID_BRD_INIT = 0,
    DRV_ID_STARS_GPIO,
    DRV_ID_DW_I2C,
    DRV_ID_HG_PVT,
    DRV_ID_STARS_PWM,
    DRV_ID_CNDS_QSPI,
    DRV_ID_STARS_SPICTRL,
    DRV_ID_STARS_V1_EFUSE,
    DRV_ID_STARS_V2_EFUSE,
    DRV_ID_DW_TRNG,
    DRV_ID_TH_TRNG,
    DRV_ID_STARS_V2_SGPIO,
    DRV_ID_STARS_V1_SGPIO,
    DRV_ID_STARS_V1P0_SGPIO,
    DRV_ID_STARS_TIMER,
    DRV_ID_STARS_UART,
    DRV_ID_STARS_WDT,
    DRV_ID_STARS_OCM_ECC,
    DRV_ID_STARS_SM3,
    DRV_ID_STARS_SM4,
    DRV_ID_STARS_TACH,
    DRV_ID_STARS_SM2,

} DrvId_e;

#define DRV_ID(type, id) ((U16)(type << 8 | id))

#define DRV_ID_BRD_INIT         DRV_ID(DEV_TYPE_BRD_INIT, DRV_ID_BRD_INIT)
#define DRV_ID_STARS_GPIO       DRV_ID(DEV_TYPE_GPIO, DRV_ID_STARS_GPIO)
#define DRV_ID_DW_I2C           DRV_ID(DEV_TYPE_I2C, DRV_ID_DW_I2C)
#define DRV_ID_HG_PVT           DRV_ID(DEV_TYPE_PVT, DRV_ID_HG_PVT)
#define DRV_ID_STARS_PWM        DRV_ID(DEV_TYPE_PWM, DRV_ID_STARS_PWM)
#define DRV_ID_CNDS_QSPI        DRV_ID(DEV_TYPE_QSPI, DRV_ID_CNDS_QSPI)
#define DRV_ID_STARS_SPICTRL    DRV_ID(DEV_TYPE_SPICTRL, DRV_ID_STARS_SPICTRL)
#define DRV_ID_STARS_V1_EFUSE      DRV_ID(DEV_TYPE_EFUSE, DRV_ID_STARS_V1_EFUSE)
#define DRV_ID_STARS_V2_EFUSE      DRV_ID(DEV_TYPE_EFUSE, DRV_ID_STARS_V2_EFUSE)
#define DRV_ID_DW_TRNG          DRV_ID(DEV_TYPE_TRNG, DRV_ID_DW_TRNG)
#define DRV_ID_TH_TRNG          DRV_ID(DEV_TYPE_TRNG, DRV_ID_TH_TRNG)
#define DRV_ID_STARS_SM3        DRV_ID(DEV_TYPE_SM3, DRV_ID_STARS_SM3)
#define DRV_ID_STARS_V2_SGPIO      DRV_ID(DEV_TYPE_SGPIO, DRV_ID_STARS_V2_SGPIO)
#define DRV_ID_STARS_V1_SGPIO      DRV_ID(DEV_TYPE_SGPIO, DRV_ID_STARS_V1_SGPIO)
#define DRV_ID_STARS_TIMER      DRV_ID(DEV_TYPE_TIMER, DRV_ID_STARS_TIMER)
#define DRV_ID_STARS_UART       DRV_ID(DEV_TYPE_UART, DRV_ID_STARS_UART)
#define DRV_ID_STARS_WDT        DRV_ID(DEV_TYPE_WDT, DRV_ID_STARS_WDT)
#define DRV_ID_STARS_OCM_ECC        DRV_ID(DEV_TYPE_OCM_ECC, DRV_ID_STARS_OCM_ECC)
#define DRV_ID_STARS_SM4        DRV_ID(DEV_TYPE_SM4, DRV_ID_STARS_SM4)
#define DRV_ID_STARS_TACH       DRV_ID(DEV_TYPE_TACH, DRV_ID_STARS_TACH)
#endif

