#!/usr/bin/env python3

def build(bld):
    # QSPI_CTRL driver
    if bld.is_defined('CONFIG_USING_QSPI_CTRL'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/qspi_ctrl/qspi_ctrl.c'
        ]