#!/usr/bin/env python3

def build(bld):
    # PWM driver
    if bld.is_defined('CONFIG_USING_PWM'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/pwm/drv_pwm.c'
        ]