#!/usr/bin/env python3

def build(bld):
    # NMEA component
    if bld.is_defined('CONFIG_USING_NMEA'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'components/nmea/tok.c'
        ]