/**
 * Copyright (C), 2023, WuXi Stars Micro System Technologies Co.,Ltd
 *
 * @file bsp_device.h
 * @author shaogl@starsmicrosystem.com
 * @date 2025.05.24
 * @brief none.
 */

#ifndef __BSP_DEVICE_H__
#define __BSP_DEVICE_H__

typedef enum DevList {
    DEVICE_PVT = 0,
    DEVICE_PVT_CH0,
    DEVICE_IOMUX,
    DEVICE_GPIO0,
    DEVICE_GPIO1,
    DEVICE_SGPIO0,
    DEVICE_SGPIO1,
    DEVICE_SGPIO2,
    DEVICE_SGPIO3,
    DEVICE_EFUSE0,
    DEVICE_SM2_0,
    DEVICE_SM3_0,
    DEVICE_SM4_0,
    DEVICE_TRNG0,
    DEVICE_QSPI0,
    DEVICE_QSPI1,
    DEVICE_DMA_0,
    DEVICE_WDT0,
    DEVICE_WDT1,
    DEVICE_WDT2,
    DEVICE_WDT3,
    DEVICE_SMBUS0,
    DEVICE_SMBUS1,
    DEVICE_SMBUS2,
    DEVICE_SMBUS3,
    DEVICE_SMBUS4,
    DEVICE_SMBUS5,
    DEVICE_SMBUS6,
    DEVICE_TACH0,
    DEVICE_TACH1,
    DEVICE_TACH2,
    DEVICE_TACH3,
    DEVICE_PWM0,
    DEVICE_UART0,
    DEVICE_UART1,
    DEVICE_I3C0,
    DEVICE_I3C1,
    DEVICE_TIMER0,
    DEVICE_TIMER1,
    DEVICE_TIMER2,
    DEVICE_TIMER3,
    DEVICE_TIMER4,
    DEVICE_TIMER5,    
    DEVICE_TIMER6,
    DEVICE_TIMER7,
    DEVICE_TIMER8,
    DEVICE_TIMER9,
    DEVICE_TIMER10,
    DEVICE_TIMER11, 

    DEVICE_CSB_GRP0,
    DEVICE_CSB_GRP1,
    DEVICE_CSB_GRP2,
    DEVICE_CSB_GRP3,
    DEVICE_CSB_GRP4,
    DEVICE_CSB_GRP5,
    DEVICE_CSB_GRP6,
    DEVICE_CSB_GRP7,
    DEVICE_CSB_GRP8,
    DEVICE_CSB_GRP9,
    DEVICE_CSB_GRP10,
    DEVICE_CSB_GRP11,
    DEVICE_CSB_GRP12,
    DEVICE_CSB_GRP13,
    DEVICE_CSB_GRP16,
    DEVICE_CSB_GRP17,
    DEVICE_CSB_GRP18,
    DEVICE_CSB_GRP19,
    DEVICE_CSB_PCIE,
    DEVICE_IMT_GRP9,
    DEVICE_OCM_ECC,

    DEVICE_NR
} DevList_e;

#endif /* __BSP_DEVICE_H__ */
