#!/usr/bin/env python3

def build(bld):
    # I2C driver
    if bld.is_defined('CONFIG_USING_SMBUS'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/smbus/source/drv_smbus_dw.c',
            'drivers/smbus/source/drv_smbus_dw_i2c.c',
            'drivers/smbus/source/drv_smbus_dw_master.c',
            'drivers/smbus/source/drv_smbus_dw_slaver.c',
            'drivers/smbus/source/drv_smbus_testsuit.c'
        ]
