#!/usr/bin/env python3

def build(bld):
    if bld.is_defined('CONFIG_DRIVER_SMBUS'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
            'drivers/smbus/source/drv_smbus_dw.c',
            'drivers/smbus/source/drv_smbus_dw_i2c.c',
            'drivers/smbus/source/drv_smbus_dw_master.c',
            'drivers/smbus/source/drv_smbus_dw_slaver.c'
        ]
