/**
 * Copyright (C), 2020, Starsmicrosystem Technologies Co.,Ltd
 *
 * @file      cli_errno.h
 * @author    xiezhj
 * @date      2021.04.08
 * @brief     文件说明
 * @note
 */

#ifndef __CLI_ERRNO_H__
#define __CLI_ERRNO_H__

#define CLI_ERRNO_INVALID (-1)

///< cli模块错误码(包含module/minor/errno字段)
typedef enum CliErrNo {

    CLI_ERRNO_OK = 0,
    CLI_ERRNO_FAILED,
    CLI_ERRNO_PARAM_NULL,
    CLI_ERRNO_PARAM_NUM_BEYOND_LIMIT,
    CLI_ERRNO_INPUT_BEYOND_LENGTH,
    CLI_ERRNO_NULL_PTR,
    CLI_ERRNO_NO_MEMORY,
    CLI_ERRNO_SESSION_FULL,
    CLI_ERRNO_NO_GETCHAR_FUNC,
    CLI_ERRNO_NO_GETS_FUNC,
    CLI_ERRNO_NO_PUTCHAR_FUNC,
    CLI_ERRNO_NO_PUTS_FUNC,
    CLI_ERRNO_SESSION_ID_UNKNOWN,
    CLI_ERRNO_ARGUMENT_INVALID,
    CLI_ERRNO_PRINT_TO_SESSION,
    CLI_ERRNO_USER_COUNT_NOT_MATCH,
    CLI_ERRNO_SESSION_STATUS_WRONG,
    CLI_ERRNO_SESSION_STATUS_UNKOWN,
    CLI_ERRNO_SESSION_PRIVATE_DATA_UESED,
    CLI_ERRNO_SESSION_PRIVATE_DATA_EMPTY,
    CLI_ERRNO_CREAT_NODE_FAIL,
    CLI_ERRNO_UNKOWN_MODULE,
    CLI_ERRNO_LEVEL_ERROR,
    CLI_ERRNO_INVAL_PARAM,
    CLI_ERRNO_INVAL_CMD,
    CLI_ERRNO_INVAL_SESSION_TYPE,
    CLI_ERRNO_SESSION_TYPE_OCCUPIED,

    CLI_ERRNO_NR,
} CliErrNo_e;

#endif ///< __CLI_ERRNO_H__
