#!/usr/bin/env python3

def build(bld):
    # Flash partition component
    if bld.is_defined('CONFIG_ENABLE_PARTITION_TABLE'):
        bld.env.PROJECT_SOURCES = getattr(bld.env, 'PROJECT_SOURCES', []) + [
                'components/flash_partition/partition_table.c',
            ]
